### ISSUE TITLE
🚗 Roadmap for v2.4.0

### ISSUE THREAD

**Issue by jgaehring** [jgaehring/jgaehring.com#2]
This version should have a complete portfolio, or "Projects" section, following on the previous version which added some polish to the general "look and feel".

Also, I'm bumping the major version to 2.x.x. I'm not sure why I was still at 0.2.0 prior to this, but I think 2.4.0 will best represent this next version, with the Jekyll version representing 1.x.x, and the minor versions corresponding to the version plan in my notes on the new site.

- [ ] Create "/projects" page
- [ ] Create routes & source content for project pages & YAML data
- [ ] Layout and style the project profile page
- [ ] Layout and style "/projects" page
- [ ] Edit Harvest Calendar profile
- [ ] Layout and style the preview on Home page
- [ ] Modify header to include main nav locations
- [ ] Create profiles for other projects
