### ISSUE TITLE
🚗 Roadmap for v2.5.0

### ISSUE THREAD

**Issue by jgaehring** [jgaehring/jgaehring.com#4]
As with 2.2, the main focus again here will be on content generation, primarily projects for my portfolio. Another blog post will be nice. And the other issues are mainly tech debt or issues which will necessarily need to be addressed by expanding the content (eg, sorting).

- [x] 4 project profiles (min. total)
- [ ] 3 blog posts (min. total)
- [x] fix graphql template deprecation warning
- [x] sort and filter project previews & blog posts
- [x] add Google Analytics
- [x] refactor graphql queries to be more reusable
- [ ] refactor project-preview to be more reusable
- [ ] work out grid/flexbox issues with post previews
